[package]
name = "musica"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
iced = "0.12.1"
native-dialog = "0.7.0"
rodio = "0.19.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
